### Linear Equation

In [1]:
import numpy as np

A = [[4, 2, -1], 
    [1, 4, 1], 
    [2, -1, 4]]
B = [5, 12, 12]

# built-in function '
x = np.linalg.solve(A, B)
x

array([1., 2., 3.])

In [2]:
import sympy as sp

u11, u12, u22, l21 = sp.symbols('u11 u12 u22 l21')

A = sp.Matrix([[1, 0], [l21, 1]])
B = sp.Matrix([[u11, u12], [0, u22]])
target = sp.Matrix([[2, 1], [1, 2]])

# Add l21 to the list of variables to solve for
solution = sp.solve(A*B - target, [u11, u12, u22, l21])

print(solution)

[(2, 1, 3/2, 1/2)]


##### Doolittle decomposition
$$
u_{ij} = a_{ij} - \sum_{k=0}^{i-1} l_{ik} \, u_{kj}, \quad j \ge i
$$
$$
l_{ij} = \frac{1}{u_{jj}}\left( a_{ij} - \sum_{k=0}^{j-1} l_{ik} \, u_{kj} \right), \quad i > j
$$

In [11]:
import numpy as np

def doolittle(A):
    n = A.shape[0]
    L = np.identity(n)
    U = np.zeros((n, n))

    for i in range(n):

        # evaluate u_ij
        for j in range(i, n):
            s = 0
            for k in range(i):
                s += L[i, k] * U[k, j]
            U[i, j] = A[i, j] - s

        # evaluate l_ij
        for j in range(i + 1, n):
            s = 0
            for k in range(i):
                s += L[j, k] * U[k, i]
            L[j, i] = (A[j, i] - s) / U[i, i]

    return L, U


A = np.array([[1, 2, 4],
              [3, 8, 14],
              [2, 6, 13]])
doolittle(A)

(array([[1., 0., 0.],
        [3., 1., 0.],
        [2., 1., 1.]]),
 array([[1., 2., 4.],
        [0., 2., 2.],
        [0., 0., 3.]]))

In [ ]:
import numpy as np

def crout(matrix):
    n = matrix.shape[0]
    L = np.zeros((n, n))
    U = np.identity(n)

    for j in range(n):
        # evaluate l_ij
        for i in range(j, n):
            s = 0
            for k in range(j):
                s += L[i, k] * U[k, j]
            L[i, j] = matrix[i, j] - s

        # evaluate u_ij
        for i in range(j + 1, n):
            s = 0
            for k in range(j):
                s += L[j, k] * U[k, i]
            U[j, i] = (matrix[j, i] - s) / L[j, j]
            
    return L, U

crout(A)


(array([[1., 0., 0.],
        [3., 2., 0.],
        [2., 2., 3.]]),
 array([[1., 2., 4.],
        [0., 1., 1.],
        [0., 0., 1.]]))